/// Flutter icons CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData more = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData car = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chat = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData comment = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData line_chart2 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData speech_bubble = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData apartment = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData magic_wand = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData drop = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData lighter = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData sort_alpha_asc = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cloud_sync = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData database = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData dice = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData star_half = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData star_empty = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData paperclip = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData printer = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData send2 = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData enter = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData exit = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData car3 = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData license = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData music_note = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData film_play = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData camera_video = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData shirt = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData store = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData cart = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData tag = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData phone_handset = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData phone = const IconData(0xe831, fontFamily: _kFontFam);
  static const IconData pushpin = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData map_marker = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe834, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData calendar_full = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData keyboard = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData spell_check = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData screen = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData smartphone = const IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData tablet = const IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData laptop = const IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData laptop_phone = const IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData power_swtich = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData lnr_bubble = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData heart_pulse = const IconData(0xe840, fontFamily: _kFontFam);
  static const IconData construction = const IconData(0xe841, fontFamily: _kFontFam);
  static const IconData pie_chart = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData chart_bars = const IconData(0xe843, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData car2 = const IconData(0xe845, fontFamily: _kFontFam);
  static const IconData car_1 = const IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData bicycle = const IconData(0xe850, fontFamily: _kFontFam);
  static const IconData wheelchair = const IconData(0xe851, fontFamily: _kFontFam);
  static const IconData select = const IconData(0xe852, fontFamily: _kFontFam);
  static const IconData earth = const IconData(0xe853, fontFamily: _kFontFam);
  static const IconData smile = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData sad = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData neutral = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData mustache = const IconData(0xe857, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData bullhorn = const IconData(0xe859, fontFamily: _kFontFam);
  static const IconData volume_high = const IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData volume_medium = const IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData volume_low = const IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData volume = const IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData mic = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData hourglass = const IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData undo = const IconData(0xe860, fontFamily: _kFontFam);
  static const IconData redo = const IconData(0xe861, fontFamily: _kFontFam);
  static const IconData sync_icon = const IconData(0xe862, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe863, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe864, fontFamily: _kFontFam);
  static const IconData download = const IconData(0xe865, fontFamily: _kFontFam);
  static const IconData upload = const IconData(0xe866, fontFamily: _kFontFam);
  static const IconData enter_down = const IconData(0xe867, fontFamily: _kFontFam);
  static const IconData exit_up = const IconData(0xe868, fontFamily: _kFontFam);
  static const IconData bug = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData code = const IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData link = const IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData unlink = const IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData magnifier = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData cross = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData chevron_up = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData chevron_down = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData chevron_right = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData arrow_down = const IconData(0xe878, fontFamily: _kFontFam);
  static const IconData arrow_left = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData arrow_right = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData move = const IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData warning = const IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData question_circle = const IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData menu_circle = const IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData checkmark_cicle = const IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData cross_circle = const IconData(0xe880, fontFamily: _kFontFam);
  static const IconData plus_circle = const IconData(0xe881, fontFamily: _kFontFam);
  static const IconData crop = const IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData frame_expand = const IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData frame_contract = const IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData layers = const IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData funnel = const IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData text_format = const IconData(0xe890, fontFamily: _kFontFam);
  static const IconData text_format_remove = const IconData(0xe891, fontFamily: _kFontFam);
  static const IconData text_size = const IconData(0xe892, fontFamily: _kFontFam);
  static const IconData bold = const IconData(0xe893, fontFamily: _kFontFam);
  static const IconData italic = const IconData(0xe894, fontFamily: _kFontFam);
  static const IconData underline = const IconData(0xe895, fontFamily: _kFontFam);
  static const IconData strikethrough = const IconData(0xe896, fontFamily: _kFontFam);
  static const IconData highlight = const IconData(0xe897, fontFamily: _kFontFam);
  static const IconData text_align_left = const IconData(0xe898, fontFamily: _kFontFam);
  static const IconData text_align_center = const IconData(0xe899, fontFamily: _kFontFam);
  static const IconData text_align_right = const IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData text_align_justify = const IconData(0xe89b, fontFamily: _kFontFam);
  static const IconData line_spacing = const IconData(0xe89c, fontFamily: _kFontFam);
  static const IconData indent_increase = const IconData(0xe89d, fontFamily: _kFontFam);
  static const IconData direction_ltr = const IconData(0xe8a0, fontFamily: _kFontFam);
  static const IconData direction_rtl = const IconData(0xe8a1, fontFamily: _kFontFam);
  static const IconData page_break = const IconData(0xe8a2, fontFamily: _kFontFam);
  static const IconData sort_amount_asc = const IconData(0xe8a4, fontFamily: _kFontFam);
  static const IconData hand = const IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData pointer_up = const IconData(0xe8a6, fontFamily: _kFontFam);
  static const IconData pointer_right = const IconData(0xe8a7, fontFamily: _kFontFam);
  static const IconData pointer_down = const IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData pointer_left = const IconData(0xe8a9, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData facebook = const IconData(0xf09a, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData google = const IconData(0xf1a0, fontFamily: _kFontFam);
}
