name: tfg_app
description: A tool to help patients suffering from amaxophobia

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.0

  # Add the dependency for the Firebase Core Flutter SDK
  # https://pub.dev/packages/firebase_core
  firebase_core: ^0.5.0

  # Add the dependency for the FlutterFire plugin for Google Analytics
  # https://pub.dev/packages/firebase_analytics
  firebase_analytics: ^6.0.0

  # A Flutter plugin to use the Firebase Authentication API and Cloud Firestore.
  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^0.18.0+1

  # A Flutter plugin to use the Cloud Firestore API.
  # https://pub.dev/packages/cloud_firestore
  cloud_firestore: ^0.14.0+2

  # A Flutter plugin to use the Firebase Cloud Storage API.
  # https://pub.dev/packages/firebase_storage
  firebase_storage: ^4.0.0

  # A Flutter plugins for Google and Facebook Sign In
  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^4.5.4

  # A Flutter plugin for using the native Facebook Login SDKs on Android and iOS.
  # https://pub.dev/packages/flutter_facebook_login
  flutter_facebook_login: ^3.0.0

  # Integrate dialogflow and support dialogflow v2
  # Locally modified files
  flutter_dialogflow: 
    path: ./flutter_dialogflow-0.1.3-hijacking/

  # Simple, fast generation of RFC4122 UUIDs.
  # https://pub.dev/packages/uuid/
  uuid: ^2.2.2

  # A Flutter plugin for launching a URL in the 
  # mobile platform. Supports iOS and Android.
  # https://pub.dev/packages/url_launcher
  url_launcher: ^5.7.2

  # String validation and sanitization for Dart
  # https://pub.dev/packages/validators/
  validators: ^2.0.1

  # Display progress widgets based on percentage
  # https://pub.dev/packages/percent_indicator
  percent_indicator: "^2.1.7+2"

  # A basic password strength estimator for Dart
  # https://pub.dev/packages/password_strength
  password_strength: ^0.1.2

  # Provides internationalization and localization facilities, 
  # including message translation, plurals and genders, date/number 
  # formatting and parsing, and bidirectional text.
  # https://pub.dev/packages/intl
  intl: ^0.16.1

  # Animation library for Flutter
  # https://pub.dev/packages/animator 
  animator: ^2.0.1

  # Wraps NSUserDefaults (on iOS) and SharedPreferences (on Android), providing a persistent store for simple data. 
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^0.5.12

  # A flutter library to show images from the internet 
  # and keep them in the cache directory
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^2.3.2+1

  # A Flutter plugin for iOS and Android for picking images 
  # from the image library, and taking new pictures with the camera.
  # https://pub.dev/packages/image_picker
  image_picker: ^0.6.7+11

  # A Flutter plugin that provides a Google Maps widget.
  # https://pub.dev/packages/google_maps_flutter
  google_maps_flutter: ^0.5.33

  # A draggable Flutter widget that makes implementing a SlidingUpPanel much easie
  # https://pub.dev/packages/sliding_up_panel
  sliding_up_panel: ^1.0.2

  # Command-line tool which simplifies the task 
  # of updating your Flutter app's launcher icon
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.8.0

  # Material Design data visualization library written natively in Dart.
  # https://pub.dev/packages/charts_flutter
  charts_flutter: ^0.9.0
  
  # A Flutter staggered grid view which supports multiple columns with rows of varying sizes.
  # https://pub.dev/packages/flutter_staggered_grid_view/
  flutter_staggered_grid_view: ^0.3.2

  # A Flutter plugin to play multiple simultaneously audio files, works for Android, iOS, macOS and web (WIP).
  # https://pub.dev/packages/audioplayers
  audioplayers: ^0.16.1

  # A flutter text to speech plugin (Swift,Java)
  # https://pub.dev/packages/flutter_tts
  flutter_tts: ^1.2.7

  # A little widget for picking durations. Heavily inspired from the Material Design time picker widget.
  # https://pub.dev/packages/flutter_duration_picker
  flutter_duration_picker: ^1.0.4

  # Highly customizable, feature-packed Flutter Calendar with gestures, animations and multiple formats.
  # https://pub.dev/packages/table_calendar
  #table_calendar: ^2.2.3

  # A date time picker form field which has material
  # design theme.
  # https://pub.dev/packages/datetime_picker_formfield
  datetime_picker_formfield: ^1.0.0

  # A tool to help you find missing, under-promoted, over-promoted, and unused dependencies.
  # https://pub.dev/packages/dependency_validator
  dependency_validator: ^1.5.0


  # Packages used for eMOVI

  # RxDart adds additional capabilities to Dart Streams and StreamControllers.
  # https://pub.dev/packages/rxdart
  rxdart: ^0.24.1

  # FlutterBlue is a bluetooth plugin for Flutter.
  # https://pub.dev/packages/flutter_blue
  flutter_blue: ^0.7.2

  # This plugin provides a cross-platform (iOS, Android) API to request permissions and check their status.
  # https://pub.dev/packages/permission_handler
  permission_handler: ^5.0.1+1


  # Localizations for the Flutter library
  flutter_localizations:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon/launcher_icon.png" 
  android: true
  ios: true



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Assets section
  assets:
    - assets/credentials.json
    - assets/images/  
    - assets/images/stress/ 

  # Fonts section 
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
        
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoRegular.ttf
        - asset: assets/fonts/NunitoBold.ttf
          weight: 700
        - asset: assets/fonts/NunitoLight.ttf
          weight: 300


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
